Text analysis
netcracker-education-center/analysis-service pull request #3
Opened 2021-02-18 12:44 UTC by s4kh4rov

2021-02-28 18:39 UTC, Rubik0000 commented on src/main/java/org/netcracker/learningcenter/utils/AnalysisUtils.java
> +                Iterator<JsonNode> iterator = node.path(COMMENTS).elements();
Why do you get on;y comments from ticket? Don't you need description?

2021-02-28 18:42 UTC, Rubik0000 commented on src/main/java/org/netcracker/learningcenter/utils/AnalysisStatus.java
> +public class AnalysisStatus {
I think you do not need this class at all you can hold statuses in ReportService

2021-02-28 18:43 UTC, Rubik0000 commented on src/main/java/org/netcracker/learningcenter/controller/NLPController.java
> +    private final ElasticsearchService elasticsearchService;
Common  code style is object fields follow after static fields

2021-03-02 19:18 UTC, Fuzzzi requested changes

2021-03-02 19:18 UTC, Fuzzzi commented on src/main/java/org/netcracker/learningcenter/controller/NLPController.java
> +    private static final String SOURCE = "source";
У тебя же есть утилити классы - перенеси эти переменные туда и вызывай их оттуда

2021-03-02 19:18 UTC, Fuzzzi commented on src/main/java/org/netcracker/learningcenter/controller/NLPController.java
> +        List<JsonNode> dataFromElastic = elasticsearchService.getDataByRequestId(requestId.asText());
получить данные из бд, хранилищ и прочего в контроллере - бэд практис.
у тебя в принципе слишком много логики в контроллере, так не должно быть. Контроллер нужен для того, чтобы принять запрос, провалидировать его отправить ответ в зависимости от полученного результата

2021-03-02 19:18 UTC, Fuzzzi commented on src/main/java/org/netcracker/learningcenter/controller/NLPController.java
> +        reportService.saveReport(report);
сохранение в хранилище и формирование отчетов тоже не надо делать в котроллере, всю эту логику тоже надо перенести в бизнес-логику

2021-03-17 17:05 UTC, closed without merging